### ISSUE TITLE
Unclear from documentation on how to get the model_id

### ISSUE THREAD

**Issue by smits** [Intermodalics/pickit-docs#49] opened 2019-11-04 08:41 UTC
Taken from https://docs.google.com/document/d/1ZpTaWTpMFnMKcZ3Vuy0LSqPB5qvFUk_-kNA23XNF9V0/edit?usp=sharing

They didn’t know that they could get the model_id via object_type. Our protocol documentation does not mention this. We have to make this more clear.

@Filipvds or @PhilColpaert Can you pick this up?

**Comment by achim-k** [comment] 2019-11-04 08:42
Duplicate of https://github.com/Intermodalics/pickit-docs-private/issues/86. Let's open issues there.

**Closed by achim-k** 2019-11-04 08:42 UTC
